---
name: betaFEC
full_name: betaFEC
type: app
owner_type: project
stage: beta
status: active
description: A new Federal Election Commission (FEC) website that will make campaign finance information more accessible and understandable to all users.
testable: true
tasks: https://github.com/18F/openFEC/issues
links:
- url: https://api.open.fec.gov/developers
  text: OpenFEC API Documentation
team:
- github: arowla
- github: emileighoutlaw
- github: jenniferthibault
- github: jmcarp
- github: LeahBannon
  role: product manager
- github: LindsayYoung
- github: noahmanger
- github: onezerojeremy
milestones:
- June 2014: Project Discovery stage started
- May 2015: Alpha testing of API and website
- July 2015: Beta testing of the API
- October 2015: Public release of beta site
partners: FEC
services:
- name: Travis CI
  category: CI
  url: https://travis-ci.org/18F/openFEC
links:
- url: https://beta.fec.gov
  text: betaFEC
- url: https://api.open.fec.gov/developers
  text: betaFEC API Documentation
contact: 
- betafeedback@fec.gov
