---
name: betaFEC
full_name: betaFEC
type: app
owner_type: project
stage: beta
status: active
description: A new Federal Election Commission (FEC) homepage that will make campaign finance information more accessible and understandable to all users.
testable: true
tasks: https://github.com/18F/openFEC/issues
links:
- url: https://api.open.fec.gov/developers
  text: OpenFEC API Documentation
team:
- github: arowla
- github: jmcarp
- github: LindsayYoung
services:
- name: Travis CI
  category: CI
  url: https://travis-ci.org/18F/openFEC
