language: python

sudo: false

cache: pip

python:
  - "3.4"

addons:
  postgresql: "9.4"

env:
  global:
    - secure: "g91vh8dURMJLmPkHOsy71zzXAFh8f0dO2S37ZTTJmndLZpvFeAqF/FmG3qdfEbFMOyoinME0e6FvDQDcHU7EjyTWTghLC0yoBZZwrMiLgL+jw1Ca+uzH/zs8X12ymZYVM6Iu3E+5hmQt1TIbC6A3/1nN1S+Zf6Z2x4IJcpANPjw=" # FEC_CF_USERNAME
    - secure: "gvnJY3O6nFnYJ8QB7xl2IAWQ/2d2eM4YP8dZXJLP/Ce/W2O2kGvhgKsj0gN2vElE5vXoVkwuUcGzMQVoBHTbfHoxwWc+XBmj6pD1Kx4UInaNDTbO8CYfw2VQruaU0IHW+tuMbIEz6VUcg7xWBYEp38/LH6hY192/AS0auFUX9I0=" # FEC_CF_PASSWORD

before_script:
  - psql -c 'create database "cfdm_unit_test";' -U postgres
  - travis_retry pip install -U pip setuptools wheel
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r requirements-dev.txt
  - travis_retry npm install -g swagger-tools

script: py.test

after_success:
  - travis_retry pip install codecov
  - codecov

before_deploy:
  - export PATH=$HOME:$PATH
  - travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.15.0"
  - tar xzvf $HOME/cf.tgz -C $HOME
  - travis_retry cf install-plugin autopilot -f -r CF-Community
  - npm install
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: invoke deploy --branch $TRAVIS_BRANCH --yes
  on:
    all_branches: true
